title: the UNTITLED podcast
description: (Devising) unqualified opinions; (Applying) filtered thoughts; (Discussing) distilled feelings. Listen in to weekly conversations between Jesse and John about various topics, typically related to feelings about current events.
author: Jesse Hart
email: untitled.hosts@gmail.com
lang: en-us
copyright: "&#x2117; &amp; &#xA9; 2020"
logo: /assets/img/logo.png
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
